### ISSUE TITLE
The Scaner MM config still references ORSX instead of Regolith.

### ISSUE THREAD

**Issue by dak180** [DMagic1/Orbital-Science#29]

**Comment by Olympic1** [comment]
In SCANsat v8.1 it still uses ORSX but in the Dev build (v9.0rc4.1) it uses Regolith. I don't know if DMagic wants to support dev builds or not.

If you want to support Regolith, documentation can be found [here](https://docs.google.com/document/d/1apMiDJDYtfGi_wznWejP5MmBjK7RxPZnRwFPCsATrIY). I can also make a pull request if you want.

**Comment by dak180** [comment]
True, but the Community Resource Pack has already moved to Regolith and there is (as far as I know) no version of ORSX that supports 0.90.0.

**Comment by DMagic1** [comment]
Fixed by df47a51c860bafef5ad24e02b61c323ab28053e0
