### ISSUE TITLE
Stock parts broken

### ISSUE THREAD

**Issue by jarnoburger** [DMagic1/Orbital-Science#31]
[LOG 00:27:18.822] [DM] DMagic Orbital Science Version: [v0.9.1.0] Loaded
[LOG 00:27:18.827] [DM] Contract Variables Set; Science Reward: 1 ; Completion Reward: 1 ; Forward Amount: 1 ; Penalty Amount: 1 ; Deadline Length: 1
[LOG 00:27:18.828] [DM] Max Contract Variables Set: Survey: 2 ; Asteroid: 1 ; Anomaly: 1 ; Magnetic: 2
[ERR 00:27:18.833] [DM] Whoops. Something really wrong happened here; stopping this contract experiment from loading...System.ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,ScienceExperiment].Add (System.String key, .ScienceExperiment value) [0x00000] in <filename unknown>:0 
  at ResearchAndDevelopment.loadExperiments () [0x00000] in <filename unknown>:0 
  at ResearchAndDevelopment.GetExperiment (System.String experimentID) [0x00000] in <filename unknown>:0 
  at DMagic.DMConfigLoader.configLoad () [0x00000] in <filename unknown>:0
[ERR 00:27:18.836] [R&D]: No Experiment definition found with id mysteryGoo

[ERR 00:27:18.837] [R&D]: No Experiment definition found with id mobileMaterialsLab

[ERR 00:27:18.838] [R&D]: No Experiment definition found with id barometerScan

[ERR 00:27:18.838] [R&D]: No Experiment definition found with id temperatureScan

[ERR 00:27:18.839] [R&D]: No Experiment definition found with id seismicScan

[ERR 00:27:18.840] [R&D]: No Experiment definition found with id gravityScan

[ERR 00:27:18.841] [R&D]: No Experiment definition found with id atmosphereAnalysis

[ERR 00:27:18.842] [R&D]: No Experiment definition found with id mysteryGoo

[ERR 00:27:18.842] [R&D]: No Experiment definition found with id mobileMaterialsLab

[ERR 00:27:18.843] [R&D]: No Experiment definition found with id barometerScan

[ERR 00:27:18.844] [R&D]: No Experiment definition found with id temperatureScan

[ERR 00:27:18.845] [R&D]: No Experiment definition found with id seismicScan

[ERR 00:27:18.845] [R&D]: No Experiment definition found with id gravityScan

[ERR 00:27:18.846] [R&D]: No Experiment definition found with id atmosphereAnalysis

[LOG 00:27:18.847] [DM] Successfully Added 13 New Experiments To Contract List
[LOG 00:27:18.848] [DM] Added 4 New Generic Backstories; 3 New Survey Backstories; 3 New Biological Backstories; 3 New Asteroid Backstories; 3 New Anomaly Backstories; 2 New Magnetic Backstories To The List
***
Stock parts will not give any science anymore..
Verion 0.9.9.1

**Comment by DMagic1** [comment]
This most likely means that you have duplicate science experiment definitions somewhere in your GameData folder. Either check for duplicates or post your entire output.log file, not just excerpts.

**Comment by jarnoburger** [comment]
I will tomorrow. have to sleep for work tomorrow. Thnx in advance. Greetings from Holland.

-----Oorspronkelijk bericht-----
Van: "DMagic" <notifications@github.com>
Verzonden: ‎27-‎1-‎2015 00:54
Aan: "DMagic1/Orbital-Science" <Orbital-Science@noreply.github.com>
CC: "jarnoburger" <jarno@lichtjes.nl>
Onderwerp: Re: [Orbital-Science] Stock parts broken (#31)

This most likely means that you have duplicate science experiment definitions somewhere in your GameData folder. Either check for duplicates or post your entire output.log file, not just excerpts.

**Comment by SkyMarshal** [comment]
I reproduced this myself...  I had two instances of some mod installed.   Do you still have this issue, @jarnoburger?

**Comment by SkyMarshal** [comment]
Update: I remembered that it was Crowd Sourced Science which I had installed twice which caused this while showering.
