### ISSUE TITLE
I wonder how this last objective gets completed....

### ISSUE THREAD

**Issue by dak180** [DMagic1/Orbital-Science#37]
![screen shot](https://cloud.githubusercontent.com/assets/324812/7213380/02b2d442-e54a-11e4-8cd1-fc546bb10636.png)

**Comment by DMagic1** [comment]
Ha, I was wondering when one of those was going to come up.

It looks like it was asking for an experiment to be completed while flying high in the atmosphere above the anomaly, which shouldn't be allowed.

You can find the contract parameters in the save file and check what it's asking for, you should still be able to complete it. Look for the line "Target_Anomaly = 8|0|mysterygoo"

The 8 corresponds to flying high in the atmosphere, that's probably what it will be.

I'm pretty sure it wants the mystery goo while flying high, that seems like the only one where that experiment is possible.
