### ISSUE TITLE
KAS/KIS Module name changed!

### ISSUE THREAD

**Issue by valuial** [DMagic1/Orbital-Science#40]
The formerly named module KASModuleGrab was moved to KIS
I'm no mod developer but as far as I can see, it is now named ModuleKISPickup in Mod KIS.

**Comment by valuial** [comment]
Excerpt from KSP.log:

[LOG 13:16:19.657] PartLoader: Compiling Part 'DMagicOrbitalScience/ProbeScience/ASERT/ASERT/dmASERT'
[ERR 13:16:19.667] Cannot find a PartModule of typename 'KASModuleGrab'

**Comment by DMagic1** [comment]
Fixed in version 1.0.4
