### ISSUE TITLE
latest Universal Storage broken with latest Orbital Science. 

### ISSUE THREAD

**Issue by VileTouch** [DMagic1/Orbital-Science#45]
wedge parts won't even open, let alone do anything else.
second to last version (1.0.4) works no problem though.

US. version 1.1.0.6
OS version 1.0.6

**Comment by VileTouch** [comment]
i understand a few internal names have changed but if both mods agree to reference the same name, already installed parts shouldn't break

**Comment by DMagic1** [comment]
1.0.7 is the latest version. 1.0.6 had some problems and was pulled from all of the download sites.
