### ISSUE TITLE
Cannot observe/collect science from PresMat/2Hot, Goo, or Sci Jr. wedges

### ISSUE THREAD

**Issue by Aetyrno** [DMagic1/Orbital-Science#46]
OS 1.0.7, US 1.1.0.6.
Win 7 (32bit client)

I can interact with the wedges, and toggle opening/closing the doors and the display on the pres/2hot, but cannot do any of the observations.  They're also not counting towards any contract requiring a satellite with that component (ex., one of the DMagic contracts required a telescope and mat bay on the satellite.  Telescope wedge counted, sci jr. wedge did not.)

The wedges based on your in-house experiments all appear to be working fine.

**Comment by Aetyrno** [comment]
Further testing, it looks like it may be some sort of incompatibility with the SETIctt mod.  Not sure if this is one you would need to address or them.

**Comment by mLuby** [comment]
I'm encountering a similar bug on the Universal Storage parts, essentially that [the situation is not allowing the experiment to happen](https://github.com/DMagic1/Orbital-Science/blob/3ccf69bd1f4d19b036525bf3e9e13ecdcf8cf49c/Source/Part%20Modules/DMModuleScienceAnimate.cs#L1015). Should I open a new issue?
