### ISSUE TITLE
Disable Multi-Spectral Imaing Scan on Energy loss.

### ISSUE THREAD

**Issue by ccaccb** [DMagic1/Orbital-Science#50]
I have noticed the following problem:
When starting a Multi-Spectral Scan and the Vessel can't generate enough electricity, the vessel switches back and forth between powered and unpowered very fast (several times per second).
This makes it impossible to deactivate the Scan and control the vessel again.

Maybe suspend the scan for 10 seconds, if no electric charge is there and then start again? This would allow for a dark period (turning the craft, dark side of planet) but get rid of the problem that the vessel is uncontrollable.

A working workaround is to switch to another craft and back, but I guess a proper fix would be better.

**Comment by DMagic1** [comment]
This is a SCANsat issue, but should be fixed in the latest version of that.
