### ISSUE TITLE
More generic asteroid handling

### ISSUE THREAD

**Issue by Starstrider42** [DMagic1/Orbital-Science#55]
I'm putting the finishing touches on an asteroid type system (Starstrider42/Custom-Asteroids#4) for Custom Asteroids. It would be helpful if other asteroid mods worked for any part containing `ModuleAsteroid`, not just `PotatoRoid`. Could the asteroid science experiments be modified to test for the part module rather than the part name?

**Comment by DMagic1** [comment]
OK. I'll have to figure out the best way to handle this when finding a raycast target, but it should be no problem.

**Comment by Starstrider42** [comment]
Thanks!
