### ISSUE TITLE
Universal Storage Mystery Goo and Science Jr. parts can not be reset/restored/cleaned-up by EVA

### ISSUE THREAD

**Issue by darchambault** [DMagic1/Orbital-Science#57]
It seems to be impossible to reset (or restore or clean-up, depending on terminology) the Universal Storage Mystery Goo and Science Jr. experiments while on EVA with a scientist, unlike the equivalent stock parts.

The data can be retrieved successfully, but since no reset is available, it's impossible to reuse the experiment.

This is running on KSP 1.1 final, with DMagic Orbital Science 1.2.3.

**Comment by DMagic1** [comment]
Should be fixed in 1.2.4
