### ISSUE TITLE
Radio Signals Intelligence Dish blocks sunlight

### ISSUE THREAD

**Issue by Maxzhao1999** [DMagic1/Orbital-Science#72]
Hi! I've encountered a little problem when using the gigantic dish. When deployed it blocking sunlight, when i accidently run out of electric charge the dish will always point at the sun until the angle between Kerbin and Sun changes which can take months, this part is more problematic than others due to its unusual size, is there a way to fix this? Or maybe this is an intended feature?

**Comment by DMagic1** [comment]
There isn't much that can be done about this, you just have to plan accordingly.
