### ISSUE TITLE
Magnometer cannot scan kerbin

### ISSUE THREAD

**Issue by toric55** [DMagic1/Orbital-Science#73]
in both stock and SCANSAT, the max altitude for the magnometer for ore scanning is 60 km. this is lower than kerbins atmosphere, and as sutch, it cannot be fesably used to scan ore there. is this intended?

**Comment by DMagic1** [comment]
This part comes very early in the tech tree, so it is intended that it has several trade-offs compared to the scanner which comes near the end. So if you want to do an Ore scan of Kerbin for whatever reason you'll have to wait for the Narrow Band scanner.
