### ISSUE TITLE
Bug crash KSP on startup

### ISSUE THREAD

**Issue by bbc25185** [DMagic1/Orbital-Science#75]
Hi...
I have KSP latest version (V. 1.3.0.1804)
Module Manager (V. 2.8.0)
I tried to remove any mod (without this and module Manager) and tried to delete the savegame... game still crash on startup!!!
I've tried both the X86 and X64 versions... no result!!!
Attach the log of the crash:
[2017-05-31_190732.zip](https://github.com/DMagic1/Orbital-Science/files/1042349/2017-05-31_190732.zip)

**Comment by DMagic1** [comment]
Should be fixed in the latest version:
https://github.com/DMagic1/Orbital-Science/releases/tag/v1.3.9
