### ISSUE TITLE
Universal Storage - Pressure/Temperature, Goo, Science Jnr., Orbital Telescope and Solar Particles experiments won't run

### ISSUE THREAD

**Issue by meatbee** [DMagic1/Orbital-Science#87]
Pressure/Temperature and Solar Particles experiments aren't clickable after placement (I had to remove them from my craft file manually), and they (in addition to the Goo, Telescope and Science Jnr.) always think they are in the wrong place to be deployed/run.
i.e. when activated through sciencealert, they all refuse to run an experiment even in the correct locations, citing the wrong conditions for their experiment (be that too atmospheric, not enough atmosphere, should be in orbit etc. even if correct conditions are met).

EDIT: I'm stupid - sorry. I'm not sure why they worked at all, since I have now found out that this mod is incompatible with Universal Storage II.
You could have fooled me; the parts looked pretty sweet and let me do things with advanced tweakables in the VAB all nice.

EDIT2: Actually, is this an old bug? #46? I don't have SETIctt installed.

**Comment by mpwoz** [comment]
I'm seeing the same issue - "mystery goo is unsafe to observe in this environment" on the wedge but the vanilla goo works perfectly. Also using US2, maybe that's the problem?

Although the US2 page says that this mod is compatible.. (http://www.kingtiger.online/uvsii/)

**Comment by markmalek** [comment]
I'm also running into the same issue with US2 installed

**Comment by DMagic1** [comment]
New versions of the Universal Storage parts have been added for use with US2.

The old versions don't work properly with US2 (despite what the PR or anyone else says) and have been deprecated.
